# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3.7'
# services:
#   peer0.org1.example.com:
#     container_name: peer0.org1.example.com
#     image: hyperledger/fabric-peer:latest
#     labels:
#       service: hyperledger-fabric
#     environment:
#       #Generic peer variables
#       - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
#       - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
#     volumes:
#       - ./docker/peercfg:/etc/hyperledger/peercfg
#       - ${DOCKER_SOCK}:/host/var/run/docker.sock

#   peer0.org2.example.com:
#     container_name: peer0.org2.example.com
#     image: hyperledger/fabric-peer:latest
#     labels:
#       service: hyperledger-fabric
#     environment:
#       #Generic peer variables
#       - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
#       - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
#     volumes:
#       - ./docker/peercfg:/etc/hyperledger/peercfg
#       - ${DOCKER_SOCK}:/host/var/run/docker.sock
  
#   cli:
#     container_name: cli
#     image: hyperledger/fabric-tools:latest
#     volumes:
#       - ./docker/peercfg:/etc/hyperledger/peercfg

volumes:
  orderer.example.com:
  peer0.org1.manufacturer.com:
  peer0.org2.wholesaler.com:
  peer0.org3.pharmacist.com:
  peer0.org4.patient.com:
  peer0.org5.auditor.com:


networks:
  test:
    name: fabric_test

services:

  orderer.example.com:
    container_name: orderer.example.com
    image: hyperledger/fabric-orderer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7053
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer.example.com:9443
      - ORDERER_METRICS_PROVIDER=prometheus
    working_dir: /root
    command: orderer
    volumes:
        - ../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
        - ../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/var/hyperledger/orderer/tls
        - orderer.example.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
      - 7053:7053
      - 9443:9443
    networks:
      - test

  peer0.org1.manufacturer.com:
    container_name: peer0.org1.manufacturer.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.org1.manufacturer.com
      - CORE_PEER_ADDRESS=peer0.org1.manufacturer.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.manufacturer.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.manufacturer.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.manufacturer.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer0.org1.manufacturer.com:9444
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0org1"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
        # - ../organizations/peerOrganizations/org1.manufacturer.com/peers/peer0.org1.manufacturer.com:/etc/hyperledger/fabric
        # - peer0.org1.manufacturer.com:/var/hyperledger/production
        - ./docker/peercfg:/etc/hyperledger/fabric
        - ${DOCKER_SOCK}:/host/var/run/docker.sock
        - ../organizations/peerOrganizations/org1.manufacturer.com/peers/peer0.org1.manufacturer.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/org1.manufacturer.com/peers/peer0.org1.manufacturer.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org1.manufacturer.com:/var/hyperledger/production
    # working_dir: /root
    # working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7051:7051
      - 9444:9444
    networks:
      - test

  
  peer0.org2.wholesaler.com:
    container_name: peer0.org2.wholesaler.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.org2.wholesaler.com
      - CORE_PEER_ADDRESS=peer0.org2.wholesaler.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org2.wholesaler.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.wholesaler.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.wholesaler.com:9051
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:19051
    volumes:
        - ./docker/peercfg:/etc/hyperledger/fabric
        - ${DOCKER_SOCK}:/host/var/run/docker.sock
        - ../organizations/peerOrganizations/org2.wholesaler.com/peers/peer0.org2.wholesaler.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/org2.wholesaler.com/peers/peer0.org2.wholesaler.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org2.wholesaler.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 9051:9051
      - 19051:19051
    networks:
      - test


## Working
  peer0.org3.pharmacist.com:
    container_name: peer0.org3.pharmacist.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG 
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.org3.pharmacist.com
      - CORE_PEER_ADDRESS=peer0.org3.pharmacist.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org3.pharmacist.com:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org3.pharmacist.com:11051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org3.pharmacist.com:11051
      - CORE_PEER_LOCALMSPID=Org3MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp      
      # - CORE_OPERATIONS_LISTENADDRESS=peer0.org3.pharmacist.com:11445
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:11445
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0org3"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
        - ./docker/peercfg:/etc/hyperledger/fabric
        - ${DOCKER_SOCK}:/host/var/run/docker.sock
        # - ../organizations/peerOrganizations/org3.pharmacist.com/peers/peer0.org3.pharmacist.com:/etc/hyperledger/fabric
        # - peer0.org3.pharmacist.com:/var/hyperledger/production
        - ../organizations/peerOrganizations/org3.pharmacist.com/peers/peer0.org3.pharmacist.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/org3.pharmacist.com/peers/peer0.org3.pharmacist.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org3.pharmacist.com:/var/hyperledger/production
    # working_dir: /root
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 11051:11051
      - 11445:11445
    networks:
      - test


  peer0.org4.patient.com:
    container_name: peer0.org4.patient.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      # - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #Generic peer variables
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.org4.patient.com
      - CORE_PEER_ADDRESS=peer0.org4.patient.com:12051
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org4.patient.com:12052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org4.patient.com:12051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org4.patient.com:12051
      - CORE_PEER_LOCALMSPID=Org4MSP
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0org4"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s      
    volumes:
        - ./docker/peercfg:/etc/hyperledger/fabric
        - ${DOCKER_SOCK}:/host/var/run/docker.sock
        # - ../../organizations/peerOrganizations/org4.patient.com/peers/peer0.org4.patient.com:/etc/hyperledger/fabric        
        # - peer0.org4.patient.com:/var/hyperledger/production
        - ../organizations/peerOrganizations/org4.patient.com/peers/peer0.org4.patient.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/org4.patient.com/peers/peer0.org4.patient.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org4.patient.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 12051:12051
    networks:
      - test

  peer0.org5.auditor.com:
    container_name: peer0.org5.auditor.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      # - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #Generic peer variables
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.org5.auditor.com
      - CORE_PEER_ADDRESS=peer0.org5.auditor.com:13051
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_LISTENADDRESS=0.0.0.0:13051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org5.auditor.com:13052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:13052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org5.auditor.com:13051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org5.auditor.com:13051
      - CORE_PEER_LOCALMSPID=Org5MSP
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0org5"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s      
    volumes:
        - ./docker/peercfg:/etc/hyperledger/fabric
        - ${DOCKER_SOCK}:/host/var/run/docker.sock
        # - ../../organizations/peerOrganizations/org5.auditor.com/peers/peer0.org5.auditor.com:/etc/hyperledger/fabric        
        # - peer0.org5.auditor.com:/var/hyperledger/production
        - ../organizations/peerOrganizations/org5.auditor.com/peers/peer0.org5.auditor.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/org5.auditor.com/peers/peer0.org5.auditor.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org5.auditor.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 13051:13051
    networks:
      - test

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    labels:
      service: hyperledger-fabric
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - FABRIC_LOGGING_SPEC=INFO
      # - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - ../organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations
        - ../scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
    depends_on:
      - peer0.org1.manufacturer.com
      - peer0.org2.wholesaler.com
      - peer0.org3.pharmacist.com
      - peer0.org4.patient.com
      - peer0.org5.auditor.com
    networks:
      - test



